name: Test Build

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: [9.x]
    
    steps:
      - uses: actions/checkout@v5
        
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore --configuration Release
      
      - name: Test with the dotnet CLI
        run: dotnet test --no-build

      - name: Upload dotnet test results
          uses: actions/upload-artifact@v4
          with:
            name: dotnet-results-${{ matrix.dotnet-version }}
            path: TestResults-${{ matrix.dotnet-version }}
          if: ${{ always() }}