name: Test Build

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: [9.x]
    
    steps:
      - uses: actions/checkout@v5
        
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Install dependencies
        run: dotnet restore Sudoku.sln
        
      - name: Build
        run: dotnet build --no-restore --configuration Release